version: '3.0'
services:
  backend1:
    build: ./backend1
    ports:
      - "3001:3001"
    networks:
      - compose-networks

  backend2:
    build: ./backend2
    ports:
      - "3002:3002"
    networks:
      - compose-networks

networks:
  compose-networks: